-- ============================================================================
-- ECOLOOP — MODULE 16: INDUSTRY DASHBOARD
-- Run this in: Supabase Dashboard -> SQL Editor -> New Query -> Run
-- Prerequisite: module3_database_schema.sql and Rls_gap_fix.sql already ran.
-- ============================================================================
-- What Module 16 needs vs. what already exists:
--
--   1. Company identity + all-time stats (`industry_profiles.waste_received_kg`,
--      `.deliveries_count`) already exist (Module 3) and are already
--      SELECT-able by their owner (`industry_profiles_owner_select`,
--      Rls_gap_fix.sql). No changes needed for those — Module 16 just reads
--      them for real instead of the mock `INITIAL_INDUSTRIES` row.
--   2. There is NO table anywhere for warehouse/silo stock levels — the old
--      UI's `stocks` object was pure local `useState`, reset on every page
--      load. This file adds a real `industry_inventory` table.
--   3. Reports/statistics are computed client-side from #1 and #2 — no
--      separate reports table is needed for Module 16.
--
-- Module 16 deliberately does NOT touch:
--   - Incoming Bulk Cargo / Accept / Reject / Processing batches — that's
--     Module 17 (Waste Management), which is what will eventually write
--     real rows into `industry_inventory` and increment
--     `industry_profiles.waste_received_kg` / `.deliveries_count` when a
--     delivery is really accepted.
--   - Company Credentials (profile editing) — that's Module 18 (Industry
--     Profile).
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. industry_inventory — one row per (industry, waste category)
-- ----------------------------------------------------------------------------
create table if not exists public.industry_inventory (
  id           bigint generated by default as identity primary key,
  industry_id  uuid not null references public.profiles(id) on delete cascade,
  category     text not null,
  quantity_kg  numeric(12,2) not null default 0.00,
  capacity_kg  numeric(12,2) not null default 20000.00,
  location     text,
  updated_at   timestamptz not null default now(),
  unique (industry_id, category)
);

alter table public.industry_inventory enable row level security;

create policy "industry_inventory_owner_select" on public.industry_inventory
  for select using (industry_id = auth.uid() or public.current_user_role() = 'admin');

create policy "industry_inventory_owner_insert" on public.industry_inventory
  for insert with check (industry_id = auth.uid());

create policy "industry_inventory_owner_update" on public.industry_inventory
  for update using (industry_id = auth.uid() or public.current_user_role() = 'admin')
  with check (industry_id = auth.uid() or public.current_user_role() = 'admin');

-- No DELETE policy — silo rows are never removed, only zeroed out, same
-- reasoning as `partner_profiles`/`customer_profiles` having no delete path.


-- ============================================================================
-- VERIFY (run after the block above)
-- ============================================================================
-- 1) Confirm the table + policies exist:
-- select policyname, cmd from pg_policies where tablename = 'industry_inventory';
--
-- 2) As a signed-in industry account, this should return 0 rows the first
--    time (the app seeds the 6 default categories on first Dashboard load):
-- select * from public.industry_inventory where industry_id = auth.uid();
--
-- 3) After the app has seeded them, this should return exactly 6 rows
--    (Paper, Plastic, Glass, Metal, E-Waste, Organic), all at 0 Kg:
-- select category, quantity_kg, capacity_kg, location
--   from public.industry_inventory where industry_id = auth.uid() order by category;
