/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * ============================================================
 *  INVOICE UTIL — Module 14 (Billing), Task 14.4
 * ============================================================
 *  Builds a real, itemized invoice from real pickup + partner
 *  data and triggers a browser download of it as a standalone,
 *  print-ready `.html` file (the person can open it and use their
 *  browser's own "Print → Save as PDF" to get a PDF, with zero new
 *  npm dependencies — consistent with this project's "no unneeded
 *  complexity" architecture decision).
 * ============================================================
 */

import type { PartnerPickup, RealPartnerProfile } from '../services/partnerService';
import { formatCurrency, formatDate } from './formatters';

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Builds the full standalone HTML document for one completed pickup's invoice. */
export function buildInvoiceHtml(pickup: PartnerPickup, partner: RealPartnerProfile): string {
  const weight = pickup.actualWeight ?? pickup.estimatedWeight;
  const amount = pickup.finalAmount ?? pickup.estimatedAmount;
  const ratePerKg = weight > 0 ? amount / weight : 0;
  const invoiceId = pickup.invoiceId ?? `PENDING-${pickup.id}`;
  const paid = pickup.paymentStatus === 'Paid';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>${escapeHtml(invoiceId)} — EcoLoop</title>
<style>
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; color: #1e293b; max-width: 640px; margin: 40px auto; padding: 0 20px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #0f172a; padding-bottom: 16px; margin-bottom: 24px; }
  .brand { font-size: 20px; font-weight: 800; }
  .status { display: inline-block; font-size: 11px; font-weight: 700; text-transform: uppercase; padding: 4px 10px; border-radius: 999px; }
  .status.paid { background: #d1fae5; color: #047857; }
  .status.pending { background: #fef3c7; color: #b45309; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px; font-size: 13px; }
  .label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; color: #94a3b8; font-weight: 700; margin-bottom: 2px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 13px; }
  th, td { text-align: left; padding: 10px 8px; border-bottom: 1px solid #e2e8f0; }
  th { font-size: 10px; text-transform: uppercase; color: #94a3b8; }
  .total-row td { font-weight: 800; font-size: 15px; border-top: 2px solid #0f172a; border-bottom: none; }
  .footer { font-size: 11px; color: #94a3b8; margin-top: 32px; text-align: center; }
  @media print { body { margin: 0; } }
</style>
</head>
<body>
  <div class="header">
    <div>
      <div class="brand">🌿 EcoLoop</div>
      <div style="font-size:11px;color:#64748b;">Recycling Pickup Invoice</div>
    </div>
    <div style="text-align:right;">
      <div style="font-weight:700;font-size:13px;">${escapeHtml(invoiceId)}</div>
      <div style="font-size:11px;color:#64748b;margin-bottom:6px;">${escapeHtml(formatDate(pickup.createdAt))}</div>
      <span class="status ${paid ? 'paid' : 'pending'}">${paid ? 'Paid' : 'Payment Pending'}</span>
    </div>
  </div>

  <div class="grid">
    <div>
      <div class="label">Billed to (Customer)</div>
      <div>${escapeHtml(pickup.customerName)}</div>
      <div style="color:#64748b;">${escapeHtml(pickup.pickupAddress)}</div>
    </div>
    <div>
      <div class="label">Collected by (Partner)</div>
      <div>${escapeHtml(partner.name)}</div>
      <div style="color:#64748b;">${escapeHtml(partner.vehicleType ?? '—')} · ${escapeHtml(partner.vehicleNumber ?? '—')}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr><th>Category</th><th>Weight (Kg)</th><th>Rate / Kg</th><th>Amount</th></tr>
    </thead>
    <tbody>
      <tr>
        <td>${escapeHtml(pickup.category)}${pickup.subcategory ? ` (${escapeHtml(pickup.subcategory)})` : ''}</td>
        <td>${weight.toFixed(2)}</td>
        <td>${formatCurrency(ratePerKg)}</td>
        <td>${formatCurrency(amount)}</td>
      </tr>
      <tr class="total-row">
        <td colspan="3">Total</td>
        <td>${formatCurrency(amount)}</td>
      </tr>
    </tbody>
  </table>

  <div class="footer">
    Request ID: ${pickup.id} · Generated by EcoLoop Drive · This is a system-generated invoice.<br/>
    Tip: use your browser's Print → "Save as PDF" to get a PDF copy of this invoice.
  </div>
</body>
</html>`;
}

/** Task 14.4 — Download invoice. Triggers a browser download of the invoice as an .html file. */
export function downloadInvoice(pickup: PartnerPickup, partner: RealPartnerProfile): void {
  const html = buildInvoiceHtml(pickup, partner);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = `${pickup.invoiceId ?? 'invoice-' + pickup.id}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}
