import {
  CustomerItem,
  PartnerItem,
  IndustryItem,
  PickupRequest,
  DIYProject,
  Transaction,
  RewardProduct,
  NotificationItem,
  PricingRate,
  SupportTicket,
  SavedAddress,
  PickupFeedback,
} from './types';

export const INITIAL_CUSTOMERS: CustomerItem[] = [
  {
    id: 'C-3829',
    name: 'Alex Rivera',
    email: 'alex.rivera@gmail.com',
    phone: '+91 98765 43210',
    address: '482 Maple Avenue, Green District',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400001',
    profilePic: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    walletBalance: 12850.00,
    rewardPoints: 2450,
    totalEarnings: 45280.00,
    status: 'Active',
  },
  {
    id: 'C-4821',
    name: 'Sarah Chen',
    email: 'sarah.c@outlook.com',
    phone: '+91 87654 32109',
    address: '88 Lotus Lane, Apt 4C',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560001',
    profilePic: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
    walletBalance: 4210.00,
    rewardPoints: 850,
    totalEarnings: 19250.00,
    status: 'Active',
  },
  {
    id: 'C-1092',
    name: 'Marcus Vance',
    email: 'marcus.v@gmail.com',
    phone: '+91 76543 21098',
    address: '1241 Cedar Court',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400002',
    profilePic: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    walletBalance: 0.00,
    rewardPoints: 120,
    totalEarnings: 1500.00,
    status: 'Suspended',
  }
];

export const INITIAL_PARTNERS: PartnerItem[] = [
  {
    id: 'P-9831',
    name: 'Daniel Cruz',
    email: 'daniel.cruz@ecoloop-partner.com',
    phone: '+91 91234 56789',
    address: '109 Pine Boulevard, East End',
    vehicleType: 'Electric Box Truck',
    vehicleNumber: 'MH-01-EL-1234',
    drivingLicense: 'DL-9823102-A',
    aadhaarNumber: '1234-5678-9012',
    profilePic: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    isOnline: true,
    rating: 4.9,
    todayPickups: 3,
    completedPickups: 142,
    earnings: 128050.00,
    distanceTraveled: 412.5,
    status: 'Approved',
  },
  {
    id: 'P-2245',
    name: 'Maya Lin',
    email: 'maya.lin@ecoloop-partner.com',
    phone: '+91 81234 56789',
    address: '439 Oak Street, Flat 2B',
    vehicleType: 'Heavy Duty Van',
    vehicleNumber: 'KA-03-EL-5678',
    drivingLicense: 'DL-4482910-B',
    aadhaarNumber: '4452-9901-8812',
    profilePic: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=200',
    isOnline: false,
    rating: 4.7,
    todayPickups: 0,
    completedPickups: 88,
    earnings: 79500.00,
    distanceTraveled: 254.0,
    status: 'Approved',
  },
  {
    id: 'P-0912',
    name: 'James Carter',
    email: 'james.carter@outlook.com',
    phone: '+91 71234 56789',
    address: '772 Birch Road',
    vehicleType: 'E-Cargo Bike',
    vehicleNumber: 'MH-02-EL-9012',
    drivingLicense: 'DL-0091244-C',
    aadhaarNumber: '9901-8823-1123',
    profilePic: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    isOnline: true,
    rating: 4.5,
    todayPickups: 1,
    completedPickups: 12,
    earnings: 11000.00,
    distanceTraveled: 48.0,
    status: 'Pending Approval',
  }
];

export const INITIAL_INDUSTRIES: IndustryItem[] = [
  {
    id: 'I-8801',
    companyName: 'EverGreen Paper Mills',
    industryType: 'Paper Recycling & Pulper',
    gstNumber: '27AAAAA1111A1Z1',
    regNumber: 'REG-88102-PVT',
    contactPerson: 'David Vance',
    email: 'contact@evergreenpaper.com',
    phone: '+91 99887 76655',
    address: 'Industrial Sector 4, Green Lane, Mumbai',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=100',
    status: 'Approved',
    wasteReceivedKg: 14500,
    deliveriesCount: 34,
  },
  {
    id: 'I-2041',
    companyName: 'Apex Poly-Polymers',
    industryType: 'Plastic Upcycling & Extrusion',
    gstNumber: '29BBBBB2222B2Z2',
    regNumber: 'REG-22041-INC',
    contactPerson: 'Elena Rostova',
    email: 'deliveries@apexpolymers.com',
    phone: '+91 88776 65544',
    address: 'Zone 11 Eco-Industrial Corridor, Bengaluru',
    logo: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=100',
    status: 'Approved',
    wasteReceivedKg: 8900,
    deliveriesCount: 22,
  },
  {
    id: 'I-4910',
    companyName: 'Nova Glassworks',
    industryType: 'Glass Crushing & Smelting',
    gstNumber: '27CCCCC3333C3Z3',
    regNumber: 'REG-49101-CORP',
    contactPerson: 'Kenji Sato',
    email: 'recycle@novaglass.co',
    phone: '+91 77665 54433',
    address: '404 Silica Drive, Glass City, Pune',
    logo: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=100',
    status: 'Pending Approval',
    wasteReceivedKg: 0,
    deliveriesCount: 0,
  }
];

export const INITIAL_PRICING_RATES: PricingRate[] = [
  { category: 'Paper', pricePerKg: 15.00, lastUpdated: '2026-07-01' },
  { category: 'Plastic', pricePerKg: 25.00, lastUpdated: '2026-07-02' },
  { category: 'Glass', pricePerKg: 10.00, lastUpdated: '2026-06-28' },
  { category: 'Metal', pricePerKg: 65.00, lastUpdated: '2026-07-05' },
  { category: 'E-Waste', pricePerKg: 120.00, lastUpdated: '2026-07-10' },
  { category: 'Cardboard', pricePerKg: 18.00, lastUpdated: '2026-07-01' },
  { category: 'Textile', pricePerKg: 8.00, lastUpdated: '2026-06-15' },
  { category: 'Organic', pricePerKg: 5.00, lastUpdated: '2026-06-30' },
  { category: 'Batteries', pricePerKg: 90.00, lastUpdated: '2026-07-12' },
  { category: 'Electronic Devices', pricePerKg: 250.00, lastUpdated: '2026-07-14' },
  { category: 'Others', pricePerKg: 7.00, lastUpdated: '2026-06-01' },
];

export const INITIAL_PICKUP_REQUESTS: PickupRequest[] = [
  {
    id: 'REQ-1094',
    customerId: 'C-3829',
    customerName: 'Alex Rivera',
    customerPhone: '+91 98765 43210',
    category: 'E-Waste',
    subcategory: 'Old Laptops & Circuit Boards',
    condition: 'Good',
    estimatedWeight: 12.5,
    actualWeight: 14.2,
    quantity: 3,
    pickupAddress: '482 Maple Avenue, Green District',
    landmark: 'Opposite Central Park Gate 2',
    preferredDate: '2026-07-15',
    preferredTime: '10:00 AM - 12:00 PM',
    images: ['https://images.unsplash.com/photo-1588508065123-287b28e013da?auto=format&fit=crop&q=80&w=300'],
    notes: 'Please bring a storage bin for batteries.',
    specialInstructions: 'Ring doorbell twice. Beware of friendly dog.',
    status: 'Assigned',
    partnerId: 'P-9831',
    partnerName: 'Daniel Cruz',
    partnerPhone: '+91 91234 56789',
    partnerLocation: { lat: 18.922, lng: 72.834 },
    estimatedAmount: 1500.00,
    finalAmount: 1704.00,
    paymentStatus: 'Pending',
    createdAt: '2026-07-13T14:32:00Z',
    assignedIndustryId: 'I-2041',
    assignedIndustryName: 'Apex Poly-Polymers',
  },
  {
    id: 'REQ-1093',
    customerId: 'C-3829',
    customerName: 'Alex Rivera',
    customerPhone: '+91 98765 43210',
    category: 'Paper',
    subcategory: 'Office Notebooks & Newspapers',
    condition: 'Excellent',
    estimatedWeight: 25.0,
    actualWeight: 24.8,
    quantity: 1,
    pickupAddress: '482 Maple Avenue, Green District',
    landmark: 'Opposite Central Park Gate 2',
    preferredDate: '2026-07-12',
    preferredTime: '02:00 PM - 04:00 PM',
    images: ['https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&q=80&w=300'],
    status: 'Completed',
    partnerId: 'P-9831',
    partnerName: 'Daniel Cruz',
    partnerPhone: '+91 91234 56789',
    estimatedAmount: 375.00,
    finalAmount: 372.00,
    paymentStatus: 'Paid',
    invoiceId: 'INV-2026-0912',
    createdAt: '2026-07-11T09:15:00Z',
    assignedIndustryId: 'I-8801',
    assignedIndustryName: 'EverGreen Paper Mills',
  },
  {
    id: 'REQ-1095',
    customerId: 'C-4821',
    customerName: 'Sarah Chen',
    customerPhone: '+91 87654 32109',
    category: 'Plastic',
    subcategory: 'PET Bottles & Food Containers',
    condition: 'Fair',
    estimatedWeight: 8.0,
    quantity: 2,
    pickupAddress: '88 Lotus Lane, Apt 4C',
    preferredDate: '2026-07-16',
    preferredTime: '09:00 AM - 11:00 AM',
    images: ['https://images.unsplash.com/photo-1618477388954-7852f32655ec?auto=format&fit=crop&q=80&w=300'],
    notes: 'All items are thoroughly washed and separated.',
    status: 'Pending',
    estimatedAmount: 200.00,
    paymentStatus: 'Unpaid',
    createdAt: '2026-07-14T03:45:00Z',
  },
  {
    id: 'REQ-1092',
    customerId: 'C-4821',
    customerName: 'Sarah Chen',
    customerPhone: '+91 87654 32109',
    category: 'Glass',
    subcategory: 'Wine & Soda Bottles',
    condition: 'Good',
    estimatedWeight: 45.0,
    actualWeight: 46.2,
    quantity: 4,
    pickupAddress: '88 Lotus Lane, Apt 4C',
    preferredDate: '2026-07-10',
    preferredTime: '11:00 AM - 01:00 PM',
    images: ['https://images.unsplash.com/photo-153693971788e-ac4f5353cc5a?auto=format&fit=crop&q=80&w=300'],
    status: 'Completed',
    partnerId: 'P-2245',
    partnerName: 'Maya Lin',
    partnerPhone: '+91 81234 56789',
    estimatedAmount: 450.00,
    finalAmount: 462.00,
    paymentStatus: 'Paid',
    invoiceId: 'INV-2026-0855',
    createdAt: '2026-07-09T08:00:00Z',
  },
  {
    id: 'REQ-1091',
    customerId: 'C-3829',
    customerName: 'Alex Rivera',
    customerPhone: '+91 98765 43210',
    category: 'Metal',
    subcategory: 'Aluminum Cans & Scrap Iron',
    condition: 'Good',
    estimatedWeight: 15.0,
    quantity: 1,
    pickupAddress: '482 Maple Avenue, Green District',
    preferredDate: '2026-07-05',
    preferredTime: '04:00 PM - 06:00 PM',
    images: ['https://images.unsplash.com/photo-1516216556131-7fa57438ece1?auto=format&fit=crop&q=80&w=300'],
    status: 'Cancelled',
    estimatedAmount: 975.00,
    paymentStatus: 'Unpaid',
    createdAt: '2026-07-04T12:00:00Z',
  }
];

export const INITIAL_DIY_PROJECTS: DIYProject[] = [
  {
    id: 'DIY-551',
    customerId: 'C-3829',
    customerName: 'Alex Rivera',
    projectName: 'Hanging Plastic Bottle Planters',
    projectDescription: 'Transformed 2L plastic soda bottles into vertical garden planters. Cleaned, cut in halves, painted with protective acrylics, filled with potting soil, and threaded together using jute twine.',
    materialsUsed: ['Plastic Bottles', 'Jute Twine', 'Acrylic Paint', 'Soil', 'Plants'],
    estimatedCost: 350.00,
    benefits: 'Diverted plastic from landfill while adding oxygen-producing greenery to a small urban balcony.',
    beforeImage: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?auto=format&fit=crop&q=80&w=200',
    afterImage: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&q=80&w=200',
    status: 'Approved',
    rewardEarned: 150,
    createdAt: '2026-07-08T10:00:00Z',
    likes: 24,
    comments: [
      { id: 'com-1', userName: 'Sarah Chen', text: 'This looks so lovely on your patio! Going to try it with my mint plant.', createdAt: '2026-07-08T14:22:00Z' },
      { id: 'com-2', userName: 'Daniel Cruz', text: 'Terrific way to repurpose the heavy plastic jugs.', createdAt: '2026-07-09T03:10:00Z' }
    ],
  },
  {
    id: 'DIY-552',
    customerId: 'C-4821',
    customerName: 'Sarah Chen',
    projectName: 'Cardboard Modular Cat Castle',
    projectDescription: 'Constructed an elaborate multi-tiered cat playhouse using sturdy delivery cardboard boxes, child-safe hot glue, and natural scratching ropes. Features peek-holes and dangling toy mice.',
    materialsUsed: ['Cardboard Boxes', 'Sisal Rope', 'Hot Glue', 'Paper Straws'],
    estimatedCost: 120.00,
    benefits: 'Repurposed cardboard packaging into durable cat enrichment furniture, saving ₹4,000 on store-bought plastic alternatives.',
    beforeImage: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&q=80&w=200',
    afterImage: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?auto=format&fit=crop&q=80&w=200',
    status: 'Pending',
    rewardEarned: 0,
    createdAt: '2026-07-13T16:15:00Z',
    likes: 8,
    comments: []
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'TXN-9023',
    userId: 'C-3829',
    type: 'Credit',
    amount: 1704.00,
    description: 'E-Waste Recycling Pickup REQ-1094',
    status: 'Completed',
    date: '2026-07-15T11:45:00Z',
  },
  {
    id: 'TXN-8823',
    userId: 'C-3829',
    type: 'Reward',
    amount: 0,
    points: 150,
    description: 'DIY Submission Approval Reward',
    status: 'Completed',
    date: '2026-07-08T10:05:00Z',
  },
  {
    id: 'TXN-4810',
    userId: 'C-3829',
    type: 'Withdrawal',
    amount: 5000.00,
    description: 'Transfer to State Bank of India Account ****9281',
    status: 'Completed',
    date: '2026-07-02T16:30:00Z',
  },
  {
    id: 'TXN-1029',
    userId: 'C-4821',
    type: 'Credit',
    amount: 462.00,
    description: 'Glass Recycling Pickup REQ-1092',
    status: 'Completed',
    date: '2026-07-10T13:10:00Z',
  }
];

export const INITIAL_REWARD_PRODUCTS: RewardProduct[] = [
  {
    id: 'REW-01',
    name: '₹1,000 Amazon Pay E-Voucher',
    description: 'Get ₹1,000 off your next purchase at Amazon India. Valid on all eco-friendly and organic store items.',
    costPoints: 500,
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=200',
    category: 'Voucher',
    available: true,
  },
  {
    id: 'REW-02',
    name: 'Plant a Native Tree in India',
    description: 'We will plant a certified native tree in your name via our partner OneTreePlanted India. Includes a digital PDF certificate.',
    costPoints: 300,
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=200',
    category: 'Tree Planting',
    available: true,
  },
  {
    id: 'REW-03',
    name: 'Eco-Friendly Reusable Bamboo Coffee Cup',
    description: 'A beautiful, insulated travel cup made of sustainable bamboo fibers. Heat-resistant and dishwasher safe. Free delivery across India.',
    costPoints: 800,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=200',
    category: 'Merchandise',
    available: true,
  },
  {
    id: 'REW-04',
    name: '1-Ton Carbon Offset Credit',
    description: 'Retire 1-ton of validated Gold Standard carbon credits. Fully offset your personal flight or monthly footprint.',
    costPoints: 1000,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=80&w=200',
    category: 'Carbon Offset',
    available: true,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NTF-1',
    userId: 'C-3829',
    role: 'customer',
    title: 'Pickup Scheduled',
    message: 'Your pickup request REQ-1094 for E-Waste has been assigned to driver Daniel Cruz.',
    type: 'success',
    read: false,
    createdAt: '2026-07-13T14:32:00Z',
  },
  {
    id: 'NTF-2',
    userId: 'C-3829',
    role: 'customer',
    title: 'DIY Project Approved!',
    message: 'Your DIY project "Hanging Plastic Bottle Planters" was approved. 150 Eco Points have been credited to your wallet!',
    type: 'success',
    read: true,
    createdAt: '2026-07-08T10:05:00Z',
  },
  {
    id: 'NTF-3',
    userId: 'all',
    role: 'all',
    title: 'New Waste Category Added',
    message: 'You can now request pickups for "Batteries" and "Electronic Devices" at higher market recycling rates!',
    type: 'info',
    read: false,
    createdAt: '2026-07-14T01:00:00Z',
  },
  {
    id: 'NTF-4',
    userId: 'P-9831',
    role: 'partner',
    title: 'New Pickup Assigned',
    message: 'You have been assigned to collect E-Waste from customer Alex Rivera (REQ-1094).',
    type: 'info',
    read: false,
    createdAt: '2026-07-13T14:32:00Z',
  },
  {
    id: 'NTF-5',
    userId: 'I-8801',
    role: 'industry',
    title: 'Incoming Delivery Confirmed',
    message: 'Driver Daniel Cruz has dispatched a batch of 24.8 kg paper scheduled to arrive today.',
    type: 'info',
    read: false,
    createdAt: '2026-07-12T09:30:00Z',
  }
];

export const WASTE_SUBCATEGORIES: Record<string, string[]> = {
  'Paper': ['Office Stationery', 'Old Newspapers', 'Magazines', 'Textbooks', 'Colored Paper'],
  'Plastic': ['PET Water Bottles', 'High-Density Jugs (HDPE)', 'PP Tupperware', 'LDPE Wrap', 'PVC Pipes'],
  'Glass': ['Wine Bottles', 'Beer Bottles', 'Mason Jars', 'Glass Container Bowls', 'Stained Pieces'],
  'Metal': ['Aluminum Beverage Cans', 'Copper Wiring', 'Iron Scraps', 'Brass Fittings', 'Steel Containers'],
  'E-Waste': ['Damaged Laptops', 'Cellphones', 'Power Chargers', 'Circuit Boards', 'Keyboards'],
  'Cardboard': ['Corrugated Shipping Boxes', 'Cereal Boxboard', 'Egg Cartons', 'Mailing Tubes'],
  'Textile': ['Cotton Clothes', 'Worn Bedding', 'Denim Scrap', 'Wool Sweaters'],
  'Organic': ['Fruit & Vegetable Scraps', 'Coffee Grounds', 'Eggshells', 'Dry Leaves', 'Yard Trimmings'],
  'Batteries': ['Li-ion Phone Batteries', 'Alkaline AA/AAA', 'Car Lead-Acid Batteries', 'Rechargeable Packs'],
  'Electronic Devices': ['LCD Computer Monitors', 'Office Laser Printers', 'Kitchen Microwaves', 'Smart Speakers'],
  'Others': ['Rubber Tires', 'Composite Materials', 'Broken Toys', 'Unsorted Goods']
};

export const INITIAL_SAVED_ADDRESSES: SavedAddress[] = [
  {
    id: 'ADR-101',
    label: 'Home',
    address: '482 Maple Avenue, Green District',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400001',
    isDefault: true,
  },
  {
    id: 'ADR-102',
    label: 'Office',
    address: 'Eco Tech Hub, Tower B, Sector 63',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400012',
    isDefault: false,
  },
  {
    id: 'ADR-103',
    label: 'Home',
    address: '88 Lotus Lane, Apt 4C',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560001',
    isDefault: true,
  }
];

export const INITIAL_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 'TCK-8012',
    userId: 'C-3829',
    userName: 'Alex Rivera',
    role: 'customer',
    subject: 'Incorrect pricing calculated for metal scrap',
    category: 'Payment Issue',
    description: 'My metal scrap was weighted 15 Kg but I received payout rates of paper in my latest invoice.',
    status: 'In-Progress',
    createdAt: '2026-07-13T09:15:00Z',
    responses: [
      { sender: 'Admin Support', text: 'Hello Alex, we are checking your verified ticket with the delivery agent Daniel Cruz. He will upload the digital photo log soon.', date: '2026-07-13T11:20:00Z' }
    ]
  },
  {
    id: 'TCK-2294',
    userId: 'P-9831',
    userName: 'Daniel Cruz',
    role: 'partner',
    subject: 'Silo scales calibration mismatch at EverGreen Paper Mills',
    category: 'Other',
    description: 'The physical receipt weigh scale at EverGreen Paper Mills showed a difference of 2.1 Kg compared to my digital truck scale. Please look into this.',
    status: 'Open',
    createdAt: '2026-07-14T02:00:00Z',
    responses: []
  },
  {
    id: 'TCK-4052',
    userId: 'C-4821',
    userName: 'Sarah Chen',
    role: 'customer',
    subject: 'Missing pickup on Monday afternoon',
    category: 'Missed Pickup',
    description: 'My request REQ-1092 was listed as in-transit but no partner arrived by 5 PM. I rescheduled it later, but wanted to let you know.',
    status: 'Resolved',
    createdAt: '2026-07-10T17:30:00Z',
    responses: [
      { sender: 'Admin Support', text: 'Apologies for the delay Sarah. We faced extreme seasonal rains causing electric vehicle grids to suspend operations. We have resolved this and processed your rescheduled slot.', date: '2026-07-11T09:00:00Z' }
    ]
  }
];

export const INITIAL_FEEDBACKS: PickupFeedback[] = [
  {
    pickupId: 'REQ-1093',
    customerRating: 5,
    customerComment: 'Daniel arrived exactly on time and helped carry the heavy cardboard stacks!',
    partnerRating: 5,
    partnerComment: 'Alex had neatly tied the newspaper bundles. Outstanding sorting cooperation!'
  },
  {
    pickupId: 'REQ-1092',
    customerRating: 4,
    customerComment: 'Prompt service, but came slightly earlier than the preferred time slot.',
    partnerRating: 5,
    partnerComment: 'Super friendly customer and clean bottles.'
  }
];

